# Go parameters
GOCMD=go
MODULENAME=github.com/biezax/wg-portal
GOFILES:=$(shell git ls-files '*.go' ':!vendor/**')
BUILDDIR=dist
BINARIES=$(subst cmd/,,$(wildcard cmd/*))
IMAGE=biezax/wg-portal
NPMCMD=npm

all: help

.PHONY: help
help:
	@echo "Usage:"
	@sed -n 's/^#>//p' ${MAKEFILE_LIST} | column -t -s ':' |  sed -e 's/^/ /'  # user commands (#>)
	@echo ""
	@echo "Advanced commands:"
	@sed -n 's/^#<//p' ${MAKEFILE_LIST} | column -t -s ':' |  sed -e 's/^/ /'  # internal commands (#<)

########################################################################################
##
## DEVELOPER / USER TARGETS
##
########################################################################################

#> codegen: Re-generate autogenerated files (like API docs)
.PHONY: codegen
codegen: $(SUBDIRS)
	cd internal; swag init --propertyStrategy pascalcase --parseInternal --generalInfo server/api.go --output server/docs/
	$(GOCMD) fmt internal/server/docs/docs.go

#> update: Update all dependencies
.PHONY: update
update:
	@ $(GOCMD) get -u ./...
	@ $(GOCMD) mod tidy

#> format: Re-format the code
.PHONY: format
format:
	@echo "Formatting code..."
	@ $(GOCMD) fmt $(GOFILES)

########################################################################################
##
## TESTING / CODE QUALITY TARGETS
##
########################################################################################

GO_TEST_IMAGE=golang:1.25
GO_DOCKER=docker run --rm -v $(PWD):/app -v wg-portal-go-cache:/go/pkg/mod -w /app $(GO_TEST_IMAGE)

#> test: Run all tests in Docker container
.PHONY: test
test: test-vet test-race

# Creates placeholder files for frontend embed directives
FRONTEND_PLACEHOLDERS=mkdir -p internal/app/api/core/frontend-dist/assets internal/app/api/core/frontend-dist/img && \
	touch internal/app/api/core/frontend-dist/index.html \
	      internal/app/api/core/frontend-dist/favicon.ico \
	      internal/app/api/core/frontend-dist/favicon.png \
	      internal/app/api/core/frontend-dist/favicon-large.png \
	      internal/app/api/core/frontend-dist/assets/placeholder.js \
	      internal/app/api/core/frontend-dist/img/placeholder.png

#< test-vet: Static code analysis in Docker
.PHONY: test-vet
test-vet:
	@$(GO_DOCKER) sh -c "$(FRONTEND_PLACEHOLDERS) && go vet ./..."

#< test-race: Race condition test in Docker
.PHONY: test-race
test-race:
	@$(GO_DOCKER) sh -c "$(FRONTEND_PLACEHOLDERS) && go mod download && go test -race -short ./..."

#< test-verbose: Verbose test output in Docker
.PHONY: test-verbose
test-verbose:
	@$(GO_DOCKER) sh -c "$(FRONTEND_PLACEHOLDERS) && go mod download && go test -race -v ./..."

#< test-pkg: Run tests for specific package (usage: make test-pkg PKG=./internal/app/wireguard/...)
.PHONY: test-pkg
test-pkg:
	@$(GO_DOCKER) sh -c "$(FRONTEND_PLACEHOLDERS) && go mod download && go test -race -v $(PKG)"

########################################################################################
##
## CI TARGETS
##
########################################################################################

#< clean: Delete all generated executables and test files
.PHONY: clean
clean:
	@rm -rf $(BUILDDIR)

#< build: Build all executables (architecture depends on build system)
.PHONY: build
build: build-dependencies
	CGO_ENABLED=0 $(GOCMD) build -o $(BUILDDIR)/wg-portal \
	 -ldflags "-w -s -extldflags \"-static\" -X 'github.com/biezax/wg-portal/internal.Version=${ENV_BUILD_IDENTIFIER}-${ENV_BUILD_VERSION}'" \
	 -tags netgo \
	 cmd/wg-portal/main.go

#< build-amd64: Build all executables for AMD64
.PHONY: build-amd64
build-amd64: build-dependencies
	CGO_ENABLED=0 $(GOCMD) build -o $(BUILDDIR)/wg-portal-amd64 \
	 -ldflags "-w -s -extldflags \"-static\" -X 'github.com/biezax/wg-portal/internal.Version=${ENV_BUILD_IDENTIFIER}-${ENV_BUILD_VERSION}'" \
	 -tags netgo \
	 cmd/wg-portal/main.go

#< build-arm64: Build all executables for ARM64
.PHONY: build-arm64
build-arm64: build-dependencies
	CGO_ENABLED=0 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 $(GOCMD) build -o $(BUILDDIR)/wg-portal-arm64 \
	 -ldflags "-w -s -extldflags \"-static\" -X 'github.com/biezax/wg-portal/internal.Version=${ENV_BUILD_IDENTIFIER}-${ENV_BUILD_VERSION}'" \
	 -tags netgo \
	 cmd/wg-portal/main.go

#< build-arm: Build all executables for ARM32
.PHONY: build-arm
build-arm: build-dependencies
	CGO_ENABLED=0 CC=arm-linux-gnueabi-gcc GOOS=linux GOARCH=arm GOARM=7 $(GOCMD) build -o $(BUILDDIR)/wg-portal-arm \
	 -ldflags "-w -s -extldflags \"-static\" -X 'github.com/biezax/wg-portal/internal.Version=${ENV_BUILD_IDENTIFIER}-${ENV_BUILD_VERSION}'" \
	 -tags netgo \
	 cmd/wg-portal/main.go

#< build-dependencies: Generate the output directory for compiled executables and download dependencies
.PHONY: build-dependencies
build-dependencies:
	@$(GOCMD) mod download -x
	@mkdir -p $(BUILDDIR)
	cp scripts/wg-portal.service $(BUILDDIR)

#< frontend: Build Vue.js frontend
frontend: frontend-dependencies
	cd frontend; $(NPMCMD) run build

#< frontend-dependencies: Generate the output directory for compiled executables and download frontend dependencies
.PHONY: frontend-dependencies
frontend-dependencies:
	@mkdir -p $(BUILDDIR)
	cd frontend; $(NPMCMD) install

#< build-docker: Build a docker image on the current host system
.PHONY: build-docker
build-docker:
	docker build --progress=plain \
	--build-arg BUILD_IDENTIFIER=${ENV_BUILD_IDENTIFIER} --build-arg BUILD_VERSION=${ENV_BUILD_VERSION} \
 	--build-arg TARGETPLATFORM=unknown . \
	-t ${IMAGE}:local

#< helm-docs: Generate the helm chart documentation
.PHONY: helm-docs
helm-docs:
	docker run --rm --volume "${PWD}/deploy:/helm-docs" -u "$$(id -u)" jnorwood/helm-docs -s file

#< run-mkdocs: Run a local instance of MkDocs
.PHONY: run-mkdocs
run-mkdocs:
	python -m venv venv; source venv/bin/activate; pip install mike cairosvg mkdocs-material mkdocs-minify-plugin mkdocs-swagger-ui-tag
	venv/bin/mkdocs serve
